In [1]:
import sys
# caution: path[0] is reserved for script path (or '' in REPL)
sys.path.insert(1, '../src')

%load_ext autoreload
%autoreload 2

import torch
import torch_geometric
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

from torch_geometric.datasets import TUDataset
from preprocessing import data_transformation
from similarity import calculate_similarity_matrix

from model import GCN

In [2]:
dataset = TUDataset(root="/", name="MUTAG")

## Preprocessing

#### Split: Train test validation

```train_dataset```: for training model<br/>
```val_dataset```: evaluate model for hyperparameter tunning<br/>
```test_dataset```: testing model after complete training<br/>

In [3]:
from torch_geometric.loader import DataLoader
from torch_geometric.data import Data

In [4]:
tr, ts, vl = 0.8, 0.1, 0.1
dslen = len(dataset)
tri = round(tr*dslen)
tsi = round((tr+ts)*dslen)
train_dataset = dataset[:tri]
test_dataset = dataset[tri:tsi]
val_dataset = dataset[tsi:]

In [5]:
dataset.y

tensor([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0])

In [6]:
print(len(train_dataset))
train_dataset.y

150


tensor([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 0, 1, 1, 0])

In [7]:
len(test_dataset)
test_dataset.y

tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [8]:
len(val_dataset)
val_dataset.y

tensor([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0])

#### Batching

In [10]:
# paper 128
batch_size = 128

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [11]:
print('train loader')
for data in train_loader:
    print(data.y)
    
print('val loader')
for data in val_loader:
    print(data.y)
    
print('test loader')
for data in test_loader:
    print(data.y)

train loader
tensor([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        1, 1, 0, 0, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0])
val loader
tensor([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0])
test loader
tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1])


## Building Model

In [12]:
from torch_geometric.nn import GCNConv
from torch.nn import Linear

from torch_geometric.nn import global_mean_pool
from torch_geometric.nn import global_add_pool

### Base model

In [13]:
class Base(torch.nn.Module):
    # merging type: o --> complement only, s --> substraction, c --> concatenation
    def __init__(self, dataset, hidden_channels):
        super(Base, self).__init__()
        
        # weight seed
        torch.manual_seed(42)
        self.conv1 = GCNConv(dataset.num_node_features, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.conv3 = GCNConv(hidden_channels, hidden_channels)
        # classification layer
        
        self.lin = Linear(hidden_channels, hidden_channels)
        self.lin2 = Linear(hidden_channels, dataset.num_classes)

    def forward(self, x, edge_index, batch):
        # Embed original
        embedding = self.conv1(x, edge_index)
        embedding = embedding.relu()
        embedding = self.conv2(embedding, edge_index)
        embedding = embedding.relu()
        embedding = self.conv3(embedding, edge_index)
        embedding = embedding.relu()
        # subgraph_embedding = subgraph_embedding.relu()
        
        embedding = global_mean_pool(embedding, batch)
        h = self.lin(embedding)
        h = h.relu()
        h = self.lin2(h)
        
        return embedding, h

In [15]:
base = Base(dataset, 64)
base

Base(
  (conv1): GCNConv(7, 64)
  (conv2): GCNConv(64, 64)
  (conv3): GCNConv(64, 64)
  (lin): Linear(in_features=64, out_features=64, bias=True)
  (lin2): Linear(in_features=64, out_features=2, bias=True)
)

In [16]:
def train_base(model, loader, experiment_mode=False):
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.05)
    
    model.train()
    
    for data in loader:
        if experiment_mode:
            emb, h = model(data.x, data.edge_index, data.batch, data.ptr)
        else:
            emb, h = model(data.x, data.edge_index, data.batch)
        loss = criterion(h, data.y)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
    return loss
    #     print(h[0])
    # print(loss)

@torch.no_grad()
def test_base(model, loader, experiment_mode=False):
    model.eval()
    correct = 0
    for data in loader:
        if experiment_mode:
            emb, h = model(data.x, data.edge_index, data.batch, data.ptr)
        else:
            emb, h = model(data.x, data.edge_index, data.batch)
        pred = h.argmax(dim=1)
        correct += int((pred == data.y).sum())
    return correct/len(loader.dataset)

base = Base(dataset, 64)
train_base(base, train_loader)

tensor(3.1258, grad_fn=<NllLossBackward0>)

In [18]:
epoch = 50

base = Base(dataset, 128)
train_base(base, train_loader)

# Train
for _ in range(epoch):
    loss = round(train_base(base, train_loader).item(), 2)
    train_acc = round(test_base(base, train_loader), 2)
    val_acc = round(test_base(base, val_loader), 2)
    
    print(f'epoch {_}; loss: {loss}; train_acc: {train_acc}; test_acc: {val_acc}')

# Test
test = test_base(base, test_loader)
print(f'Accuracy: {test}')

epoch 0; loss: 0.83; train_acc: 0.66; test_acc: 0.63
epoch 1; loss: 1.33; train_acc: 0.66; test_acc: 0.63
epoch 2; loss: 1.77; train_acc: 0.66; test_acc: 0.63
epoch 3; loss: 0.97; train_acc: 0.66; test_acc: 0.63
epoch 4; loss: 1.45; train_acc: 0.66; test_acc: 0.63
epoch 5; loss: 1.67; train_acc: 0.66; test_acc: 0.63
epoch 6; loss: 0.76; train_acc: 0.66; test_acc: 0.63
epoch 7; loss: 0.76; train_acc: 0.66; test_acc: 0.63
epoch 8; loss: 0.79; train_acc: 0.66; test_acc: 0.63
epoch 9; loss: 0.81; train_acc: 0.66; test_acc: 0.63
epoch 10; loss: 0.91; train_acc: 0.66; test_acc: 0.63
epoch 11; loss: 1.03; train_acc: 0.66; test_acc: 0.63
epoch 12; loss: 1.21; train_acc: 0.66; test_acc: 0.63
epoch 13; loss: 1.1; train_acc: 0.66; test_acc: 0.63
epoch 14; loss: 1.38; train_acc: 0.66; test_acc: 0.63
epoch 15; loss: 1.09; train_acc: 0.66; test_acc: 0.63
epoch 16; loss: 1.54; train_acc: 0.66; test_acc: 0.63
epoch 17; loss: 2.34; train_acc: 0.66; test_acc: 0.63
epoch 18; loss: 0.72; train_acc: 0.34; 

### Experiment Model

In [19]:
from sklearn.cluster import AffinityPropagation

In [20]:
class Experiment(torch.nn.Module):
    # merging type: o --> complement only, s --> substraction, c --> concatenation
    def __init__(self, dataset, hidden_channels):
        super(Experiment, self).__init__()
        
        # weight seed
        torch.manual_seed(42)
        self.conv1 = GCNConv(dataset.num_node_features, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        # classification layer
        
        self.lin = Linear(hidden_channels, hidden_channels)
        self.lin2 = Linear(hidden_channels, dataset.num_classes)

    def forward(self, x, edge_index, batch):
        # Embed original
        embedding = self.conv1(x, edge_index)
        embedding = embedding.relu()
        embedding = self.conv2(embedding, edge_index)
        
        # generate subgraph based on embeddings
        feature_emb = embedding.detach()
        G = data_transformation(edge_index, feature_emb)
        S = calculate_similarity_matrix(G)
        # clustering = AffinityPropagation(affinity='precomputed', random_state=123, max_iter=200).fit(S)
        
        embedding = global_mean_pool(embedding, batch)
        h = self.lin(embedding)
        h = h.relu()
        h = self.lin2(h)
        
        return embedding, h

    def data_transformation():
        print('s')
        


experiment = Experiment(dataset, 64)
# train_base(experiment, train_loader)

In [21]:
batch1 = None
for batch in train_loader:
    batch1 = batch
    break
print(batch1)
print(batch1.batch)
print("edge_index", batch1.edge_index)
print("batch",batch1.edge_attr)
print("ptr",batch1.ptr)

DataBatch(edge_index=[2, 5210], x=[2347, 7], edge_attr=[5210, 4], y=[128], batch=[2347], ptr=[129])
tensor([  0,   0,   0,  ..., 127, 127, 127])
edge_index tensor([[   0,    0,    1,  ..., 2345, 2346, 2346],
        [   1,    5,    0,  ..., 2346, 2334, 2345]])
batch tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        ...,
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
ptr tensor([   0,   17,   30,   43,   62,   73,  101,  117,  137,  149,  166,  183,
         203,  225,  238,  257,  279,  290,  307,  320,  338,  356,  373,  396,
         423,  440,  453,  476,  493,  516,  539,  561,  585,  608,  621,  638,
         652,  669,  684,  699,  712,  729,  742,  761,  778,  790,  813,  835,
         852,  872,  888,  914,  940,  959,  978,  992, 1009, 1030, 1055, 1078,
        1097, 1114, 1125, 1148, 1168, 1184, 1200, 1220, 1243, 1262, 1276, 1302,
        1318, 1334, 1357, 1375, 1385, 1401, 1417, 1434, 1453, 1465, 1490, 1506,

In [22]:
print(max(batch1.edge_index[0]))
print(max(batch1.edge_index[1]))
print((dataset[0].edge_index))
print((batch1.ptr), '; len:', len(batch1.ptr))

tensor(2346)
tensor(2346)
tensor([[ 0,  0,  1,  1,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  6,  6,  7,  7,
          8,  8,  8,  9,  9,  9, 10, 10, 11, 11, 12, 12, 12, 13, 13, 14, 14, 14,
         15, 16],
        [ 1,  5,  0,  2,  1,  3,  2,  4,  9,  3,  5,  6,  0,  4,  4,  7,  6,  8,
          7,  9, 13,  3,  8, 10,  9, 11, 10, 12, 11, 13, 14,  8, 12, 12, 15, 16,
         14, 14]])
tensor([   0,   17,   30,   43,   62,   73,  101,  117,  137,  149,  166,  183,
         203,  225,  238,  257,  279,  290,  307,  320,  338,  356,  373,  396,
         423,  440,  453,  476,  493,  516,  539,  561,  585,  608,  621,  638,
         652,  669,  684,  699,  712,  729,  742,  761,  778,  790,  813,  835,
         852,  872,  888,  914,  940,  959,  978,  992, 1009, 1030, 1055, 1078,
        1097, 1114, 1125, 1148, 1168, 1184, 1200, 1220, 1243, 1262, 1276, 1302,
        1318, 1334, 1357, 1375, 1385, 1401, 1417, 1434, 1453, 1465, 1490, 1506,
        1517, 1540, 1563, 1579, 1591, 1604, 1627, 165

In [23]:
graph_bound = {}

for i in range(len(batch1.ptr)-1):
    graph_bound[i] = [batch1.ptr[i].item(), batch1.ptr[i+1].item()]
    print(str(i)+".", batch1.ptr[i].item(), "-", batch1.ptr[i+1].item())

0. 0 - 17
1. 17 - 30
2. 30 - 43
3. 43 - 62
4. 62 - 73
5. 73 - 101
6. 101 - 117
7. 117 - 137
8. 137 - 149
9. 149 - 166
10. 166 - 183
11. 183 - 203
12. 203 - 225
13. 225 - 238
14. 238 - 257
15. 257 - 279
16. 279 - 290
17. 290 - 307
18. 307 - 320
19. 320 - 338
20. 338 - 356
21. 356 - 373
22. 373 - 396
23. 396 - 423
24. 423 - 440
25. 440 - 453
26. 453 - 476
27. 476 - 493
28. 493 - 516
29. 516 - 539
30. 539 - 561
31. 561 - 585
32. 585 - 608
33. 608 - 621
34. 621 - 638
35. 638 - 652
36. 652 - 669
37. 669 - 684
38. 684 - 699
39. 699 - 712
40. 712 - 729
41. 729 - 742
42. 742 - 761
43. 761 - 778
44. 778 - 790
45. 790 - 813
46. 813 - 835
47. 835 - 852
48. 852 - 872
49. 872 - 888
50. 888 - 914
51. 914 - 940
52. 940 - 959
53. 959 - 978
54. 978 - 992
55. 992 - 1009
56. 1009 - 1030
57. 1030 - 1055
58. 1055 - 1078
59. 1078 - 1097
60. 1097 - 1114
61. 1114 - 1125
62. 1125 - 1148
63. 1148 - 1168
64. 1168 - 1184
65. 1184 - 1200
66. 1200 - 1220
67. 1220 - 1243
68. 1243 - 1262
69. 1262 - 1276
70. 1276 - 13

Below --> Subgraph extractor with batch information

In [24]:
# idx_from = 0
# idx_to = 0
graph_counter = 0
graph_bound
edge_index = [[],[]]
Gs = []

from similarity import calculate_similarity_matrix, testt
# AP Clustering
from sklearn.cluster import AffinityPropagation

print(f'=== Graph {graph_counter} ===')
for i, (src, dst) in enumerate(zip(batch1.edge_index[0], batch1.edge_index[1])):
    # if (graph_counter < len(batch1.ptr)):
    lower_bound = graph_bound[graph_counter][0]
    upper_bound = graph_bound[graph_counter][1]
    if ((src >= lower_bound and src < upper_bound) or
        (dst >= lower_bound and dst < upper_bound)):
        # print(i,src.item()-lower_bound, dst.item()-lower_bound)
        edge_index[0].append(src - lower_bound)
        edge_index[1].append(dst - lower_bound)
    else:
        # print(edge_index)
        embs = []
        # make new graph
        for i, (b, emb) in enumerate(zip(batch1.batch, batch1.x)):
            if (b == graph_counter):
                # print(i, emb)
                embs.append(emb)
        
        G = data_transformation(edge_index, embs)
        Gs.append(G)
        print(sorted(list(G.nodes)))
        # print('pre', precalc_shortest_path_length)
        # for node in sorted(list(G.nodes)):
        #     print(G.nodes[node])
        
        
        # testt()
        if graph_counter == 10:
            print('masalah disini bro')
            break
        
        # Calculate S matrix
        S = calculate_similarity_matrix(G)
        
        # AP Clustering
        clustering = AffinityPropagation(affinity='precomputed', damping=0.9, random_state=123, max_iter=1000).fit(S)

        print(clustering.labels_)
        # print(clustering.)
        
        communities = {}
        print(set(clustering.labels_))
        # communities init
        for lab in clustering.labels_:
            communities[lab] = []
        
        for nd, clust in enumerate(clustering.labels_):
            communities[clust].append(nd)
        print("communities", communities) 
            
        edge_index = [[],[]]
        graph_counter+=1
        print("embs",embs)
        # print(S)
        break
        print(f'=== Graph {graph_counter} ===')
        
    if i == len(batch1.edge_index[0]) - 1:
        embs = []
        # make new graph
        for i, (b, emb) in enumerate(zip(batch1.batch, batch1.x)):
            if (b == graph_counter):
                # print(i, emb)
                embs.append(emb)
        
        G = data_transformation(edge_index, embs)
        Gs.append(G)
        
        S = calculate_similarity_matrix(G)
        # AP Clustering        
        clustering = AffinityPropagation(affinity='precomputed', damping=0.9, random_state=123, max_iter=1000).fit(S)
        
        print(sorted(list(G.nodes)))
        print(clustering.labels_)
        
        # print(edge_index)
        print('udh di akhir')

=== Graph 0 ===
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
[0 0 0 0 0 0 2 2 2 2 2 1 2 2 1 1 1]
{0, 1, 2}
communities {0: [0, 1, 2, 3, 4, 5], 2: [6, 7, 8, 9, 10, 12, 13], 1: [11, 14, 15, 16]}
embs [tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([1., 0., 0., 0., 0., 0., 0.]), tensor([0., 1., 0., 0., 0., 0., 0.]), tensor([0., 0., 1., 0., 0., 0., 0.]), tensor([0., 0., 1., 0., 0., 0., 0.])]


In [25]:
clustering = AffinityPropagation(affinity='precomputed', damping=0.7, random_state=42, convergence_iter=15, max_iter=1000)
clustering.fit(S)
clustering.labels_
# clustering.

array([0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1], dtype=int64)

In [26]:
s = [
[
0.8,
994.158268226589,
7.9207682265892885,
101.35826822658926,
561.9082682265891,
1.12076822658929,
10.80680355293715,
8.106803552937151,
73933.09430355292,
720.1082682265892,
35.22076822658928,
177.12076822658926,
572.5582682265891,
88.30826822658926,
423.30826822658923,
16.308268226589284,
],
[
994.158268226589,
0.8,
59.80680355293714,
159.72076822658926,
96.90826822658927,
110.55826822658926,
120.15826822658926,
13.720768226589287,
68123.92242855292,
556.6207682265892,
177.12076822658926,
567.406803552937,
8.558268226589288,
414.1582682265892,
744.3082682265891,
101.54430355293712,
],
[
7.9207682265892885,
59.80680355293714,
0.8,
1575.4207682265887,
11.358268226589288,
13.720768226589287,
36.55826822658928,
409.62076822658923,
93229.80680355291,
561.9082682265891,
561.9082682265891,
99.30680355293713,
48.15826822658928,
423.30826822658923,
296.55826822658923,
525.6068035529371,
],
[
101.35826822658926,
159.72076822658926,
1575.4207682265887,
0.8,
1411.3082682265888,
541.094303552937,
400.62076822658923,
270.22076822658926,
69738.34430355292,
13.90680355293715,
1411.3082682265888,
2553.9082682265885,
9.908268226589287,
702.406803552937,
285.12076822658923,
165.42076822658927,
],
[
561.9082682265891,
96.90826822658927,
11.358268226589288,
1411.3082682265888,
0.8,
180.10826822658927,
56.22076822658928,
0.72076822658929,
81409.09430355292,
556.6207682265892,
0.49430355293715383,
51.30826822658928,
42.34430355293714,
1377.908268226589,
7.4943035529371524,
891.2207682265891,
],
[
1.12076822658929,
110.55826822658926,
13.720768226589287,
541.094303552937,
180.10826822658927,
0.8,
54.55826822658928,
738.2207682265891,
77937.90680355292,
49.90680355293714,
96.90826822658927,
409.62076822658923,
304.30826822658923,
39.49430355293714,
195.42076822658925,
0.15826822658929016,
],
[
10.80680355293715,
120.15826822658926,
36.55826822658928,
400.62076822658923,
56.22076822658928,
54.55826822658928,
0.8,
97.09430355293713,
68416.04742855292,
316.12076822658923,
405.1082682265892,
262.92076822658925,
13.720768226589287,
6.720768226589289,
51.30826822658928,
94.72076822658927,
],
[
8.106803552937151,
13.720768226589287,
409.62076822658923,
270.22076822658926,
0.72076822658929,
738.2207682265891,
97.09430355293713,
0.8,
77128.49430355291,
40.72076822658928,
195.42076822658925,
427.9207682265892,
2184.158268226589,
690.4207682265892,
37.92076822658928,
12.908268226589287,
],
[
73933.09430355292,
68123.92242855292,
93229.80680355291,
69738.34430355292,
81409.09430355292,
77937.90680355292,
68416.04742855292,
77128.49430355291,
0.8,
77626.09430355292,
81409.09430355292,
77377.09430355292,
67832.42242855292,
69915.60680355292,
72390.82242855291,
70033.90680355292,
],
[
720.1082682265892,
556.6207682265892,
561.9082682265891,
13.90680355293715,
556.6207682265892,
49.90680355293714,
316.12076822658923,
40.72076822658928,
77626.09430355292,
0.8,
583.3082682265891,
99.12076822658926,
42.15826822658928,
103.80680355293713,
540.9082682265891,
234.72076822658926,
],
[
35.22076822658928,
177.12076822658926,
561.9082682265891,
1411.3082682265888,
0.49430355293715383,
96.90826822658927,
405.1082682265892,
195.42076822658925,
81409.09430355292,
583.3082682265891,
0.8,
208.12076822658926,
270.4068035529371,
177.12076822658926,
97.09430355293713,
159.72076822658926,
],
[
177.12076822658926,
567.406803552937,
99.30680355293713,
2553.9082682265885,
51.30826822658928,
409.62076822658923,
262.92076822658925,
427.9207682265892,
77377.09430355292,
99.12076822658926,
208.12076822658926,
0.8,
374.2207682265892,
270.22076822658926,
94.72076822658927,
904.806803552937,
],
[
572.5582682265891,
8.558268226589288,
48.15826822658928,
9.908268226589287,
42.34430355293714,
304.30826822658923,
13.720768226589287,
2184.158268226589,
67832.42242855292,
42.15826822658928,
270.4068035529371,
374.2207682265892,
0.8,
0.3082682265892901,
1702.3068035529368,
37.92076822658928,
],
[
88.30826822658926,
414.1582682265892,
423.30826822658923,
702.406803552937,
1377.908268226589,
39.49430355293714,
6.720768226589289,
690.4207682265892,
69915.60680355292,
103.80680355293713,
177.12076822658926,
270.22076822658926,
0.3082682265892901,
0.8,
10.620768226589288,
1702.1207682265888,
],
[
423.30826822658923,
744.3082682265891,
296.55826822658923,
285.12076822658923,
7.4943035529371524,
195.42076822658925,
51.30826822658928,
37.92076822658928,
72390.82242855291,
540.9082682265891,
97.09430355293713,
94.72076822658927,
1702.3068035529368,
10.620768226589288,
0.8,
9.908268226589287,
],
[
16.308268226589284,
101.54430355293712,
525.6068035529371,
165.42076822658927,
891.2207682265891,
0.15826822658929016,
94.72076822658927,
12.908268226589287,
70033.90680355292,
234.72076822658926,
159.72076822658926,
904.806803552937,
37.92076822658928,
1702.1207682265888,
9.908268226589287,
0.8,
],
]

In [27]:
clustering = AffinityPropagation(affinity='precomputed', damping=0.7, random_state=42, convergence_iter=15, max_iter=1000)
S = np.array(S)
print(S)
max_value = np.max(S)
np.fill_diagonal(S, max_value)
clustering.fit(S)
clustering.labels_
# clustering.

[[8.00000000e-01 1.04474286e+01 8.55826823e+00 1.03399180e+04
  1.09045583e+04 6.30297429e+02 1.18867955e+02 2.08027153e+02
  4.65178904e+01 4.56027153e+02 1.16335154e+01 1.20144830e+01
  1.16288545e+01 1.20144830e+01 2.68370102e-04 9.87278433e-05
  9.87278433e-05]
 [1.04474286e+01 8.00000000e-01 9.83797429e+02 8.88322077e+03
  5.33831795e+03 4.23308268e+02 1.27152511e-01 5.28178904e+01
  1.12827153e+02 1.22465233e+03 1.98464653e+02 5.39035760e-03
  1.20144830e+01 1.78903576e-02 1.16288545e+01 2.68370102e-04
  2.68370102e-04]
 [8.55826823e+00 9.83797429e+02 8.00000000e-01 1.56662974e+04
  5.46162077e+03 6.64167955e+02 4.46552330e+02 1.46525111e-02
  1.16679547e+01 7.87620768e+02 4.89829655e-01 1.98464653e+02
  2.98383515e+02 1.12827153e+02 1.20144830e+01 7.29505572e-04
  4.65132295e+01]
 [1.03399180e+04 8.88322077e+03 1.56662974e+04 8.00000000e-01
  4.23434430e+03 1.06031208e+04 1.88190827e+03 3.46567955e+02
  1.04412077e+03 9.16724286e+01 1.37790827e+03 8.98296547e-02
  2.11152715e+03

array([0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1], dtype=int64)

In [28]:
dataset[3].x


tensor([[1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.]])

In [29]:
for node in Gs[6].nodes:
    print(Gs[0].nodes[node])
    # Udah bisa tambah nodes per batch, tinggal masukin ke algo utama

IndexError: list index out of range

In [ ]:
dataset[63].edge_index

tensor([[ 0,  0,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  5,  5,  5,  6,  6,  6,
          7,  8,  9,  9,  9, 10, 11, 11, 11, 12, 12, 12, 13, 13, 14, 14, 15, 15,
         15, 16, 16, 17, 17, 17, 18, 19],
        [ 1,  5,  0,  2,  1,  3, 12,  2,  4,  9,  3,  5,  0,  4,  6,  5,  7,  8,
          6,  6,  3, 10, 11,  9,  9, 12, 16,  2, 11, 13, 12, 14, 13, 15, 14, 16,
         17, 11, 15, 15, 18, 19, 17, 17]])

In [30]:
for i, (b, emb) in enumerate(zip(batch1.batch, batch1.x)):
    if (b == 0):
        print(i, emb)

0 tensor([1., 0., 0., 0., 0., 0., 0.])
1 tensor([1., 0., 0., 0., 0., 0., 0.])
2 tensor([1., 0., 0., 0., 0., 0., 0.])
3 tensor([1., 0., 0., 0., 0., 0., 0.])
4 tensor([1., 0., 0., 0., 0., 0., 0.])
5 tensor([1., 0., 0., 0., 0., 0., 0.])
6 tensor([1., 0., 0., 0., 0., 0., 0.])
7 tensor([1., 0., 0., 0., 0., 0., 0.])
8 tensor([1., 0., 0., 0., 0., 0., 0.])
9 tensor([1., 0., 0., 0., 0., 0., 0.])
10 tensor([1., 0., 0., 0., 0., 0., 0.])
11 tensor([1., 0., 0., 0., 0., 0., 0.])
12 tensor([1., 0., 0., 0., 0., 0., 0.])
13 tensor([1., 0., 0., 0., 0., 0., 0.])
14 tensor([0., 1., 0., 0., 0., 0., 0.])
15 tensor([0., 0., 1., 0., 0., 0., 0.])
16 tensor([0., 0., 1., 0., 0., 0., 0.])


#### Model modification

In [26]:

# idx_from = 0
# idx_to = 0
graph_counter = 0
graph_bound
edge_index = [[],[]]
subgraph_edge_index = [[],[]]
Gs = []
sub_created = False
from similarity import calculate_similarity_matrix, testt
# AP Clustering
from sklearn.cluster import AffinityPropagation

batches = []
for b in train_loader:
    batches.append(b)
batch1 = batches[2]
print(batch1)

# return 0
graph_bound = {}

for i in range(len(batch1.ptr)-1):
    graph_bound[i] = [batch1.ptr[i].item(), batch1.ptr[i+1].item()]
    # print(str(i)+".", batch1.ptr[i].item(), "-", batch1.ptr[i+1].item())

for i, (src, dst) in enumerate(zip(batch1.edge_index[0], batch1.edge_index[1])):
    # if (graph_counter < len(batch1.ptr)):
    lower_bound = graph_bound[graph_counter][0]
    upper_bound = graph_bound[graph_counter][1]
    if ((src >= lower_bound and src < upper_bound) or
        (dst >= lower_bound and dst < upper_bound)):
        # print(i,src.item()-lower_bound, dst.item()-lower_bound)
        edge_index[0].append(src - lower_bound)
        edge_index[1].append(dst - lower_bound)
    else:
        sub_created = True
        # continue
        
        
        # # print(edge_index)
        # embs = []
        # # make new graph
        # for i, (b, emb) in enumerate(zip(batch1.batch, batch1.x)):
        #     if (b == graph_counter):
        #         # print(i, emb)
        #         embs.append(emb)
        
        # G = data_transformation(edge_index, embs)
        # Gs.append(G)
        # print(sorted(list(G.nodes)))
        # # print('pre', precalc_shortest_path_length)
        # # for node in sorted(list(G.nodes)):
        # #     print(G.nodes[node])
        
        
        # # testt()
        # if graph_counter == 10:
        #     print('masalah disini bro')
        #     break
        
        # # Calculate S matrix
        # S = calculate_similarity_matrix(G)
        
        # # AP Clustering
        # clustering = AffinityPropagation(affinity='precomputed', damping=0.9, random_state=123, max_iter=1000).fit(S)

        # print(clustering.labels_)
        # # print(clustering.)
        
        # communities = {}
        # print("cluster labels:", set(clustering.labels_))
        # # communities init
        # for lab in clustering.labels_:
        #     communities[lab] = []
        
        # for nd, clust in enumerate(clustering.labels_):
        #     communities[clust].append(nd)
        # print("communities", communities) 
            
        # edge_index = [[],[]]
        # graph_counter+=1
        
        # # make subgraph edge_index
        # for c in communities:
        #     w = G.subgraph(communities[c])
        #     # print("edges subgraph", w.edges)
        #     for sub in w.edges:
        #         # print(sub[0], sub[1])
        #         subgraph_edge_index[0].append(sub[0] + lower_bound)
        #         subgraph_edge_index[1].append(sub[1] + lower_bound)
                
        # print(subgraph_edge_index)
        # print(f'=== Graph {graph_counter} ===') 
        
    if (i == len(batch1.edge_index[0]) - 1) or sub_created:
        print(f'=== Graph {graph_counter} ===')
        
        sub_created = False
        
        embs = []
        # make new graph
        for i, (b, emb) in enumerate(zip(batch1.batch, batch1.x)):
            if (b == graph_counter):
                # print(i, emb)
                embs.append(emb)
        
        G = data_transformation(edge_index, embs)
        print(G)
        print("edge_idx", edge_index)
        print(max(G.nodes))
        print(len(G.nodes))
        
        Gs.append(G)
        
        S = calculate_similarity_matrix(G)
        # AP Clustering        
        clustering = AffinityPropagation(affinity='precomputed', damping=0.9, random_state=123, max_iter=1000).fit(S)
        
        print(sorted(list(G.nodes)))
        print(clustering.labels_)
        
        # Modif disini nanti
        #########
        communities = {}
        # print("cluster labels:", set(clustering.labels_))
        # communities init
        for lab in clustering.labels_:
            communities[lab] = []
        
        for nd, clust in enumerate(clustering.labels_):
            communities[clust].append(nd)
        # print("communities", communities) 
            
        edge_index = [[],[]]
        graph_counter+=1
        
        # make subgraph edge_index
        for c in communities:
            w = G.subgraph(communities[c])
            # print("edges subgraph", w.edges)
            for sub in w.edges:
                # print(sub[0], sub[1])
                subgraph_edge_index[0].append(sub[0] + lower_bound)
                subgraph_edge_index[1].append(sub[1] + lower_bound)
                
        print(subgraph_edge_index)
        if (graph_counter == 10):
            break
        # print(f'=== Graph {graph_counter} ===')
        # print(edge_index)
        # print('udh di akhir')

embeddings_used = []
nodes_used = set(np.array(subgraph_edge_index).flatten())
feat = batch1.x
# for i, f in enumerate(feat):
#     if(i in nodes_used):
#         embeddings_used.append(feat[i].detach().numpy())
        
# print(len(embeddings_used))
# z = torch.zeros(len(embeddings_used), len(embeddings_used[0]))
# z = torch.tensor(embeddings_used)

# print(torch.tensor(subgraph_edge_index).size())
# nodes_used = set(np.array(subgraph_edge_index).flatten())
# feat = batch1.x
# for i, f in enumerate(feat):
#     if(i in nodes_used):
#         print(i)

DataBatch(edge_index=[2, 720], x=[337, 7], edge_attr=[720, 4], y=[22], batch=[337], ptr=[23])
=== Graph 0 ===
Graph with 14 nodes and 14 edges
edge_idx [[tensor(0), tensor(0), tensor(1), tensor(1), tensor(2), tensor(2), tensor(2), tensor(3), tensor(3), tensor(3), tensor(4), tensor(4), tensor(5), tensor(5), tensor(5), tensor(6), tensor(6), tensor(6), tensor(7), tensor(8), tensor(9), tensor(9), tensor(9), tensor(10), tensor(11), tensor(12), tensor(12), tensor(13)], [tensor(1), tensor(5), tensor(0), tensor(2), tensor(1), tensor(3), tensor(12), tensor(2), tensor(4), tensor(9), tensor(3), tensor(5), tensor(0), tensor(4), tensor(6), tensor(5), tensor(7), tensor(8), tensor(6), tensor(6), tensor(3), tensor(10), tensor(11), tensor(9), tensor(9), tensor(2), tensor(13), tensor(12)]]
13
14
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[0 0 2 1 1 0 0 0 0 1 1 1 2 2]
[[0, 0, 5, 6, 6, 2, 12, 3, 3, 9, 9], [1, 5, 6, 7, 8, 12, 13, 4, 9, 10, 11]]
=== Graph 1 ===
Graph with 11 nodes and 11 edges
edge_idx 

In [94]:

from similarity import calculate_similarity_matrix, testt


# AP Clustering
from sklearn.cluster import AffinityPropagation

from torch_geometric.nn import global_mean_pool
from torch_geometric.nn import global_max_pool

import torch.nn.functional as F

class Experiment(torch.nn.Module):
    # merging type: o --> complement only, s --> substraction, c --> concatenation
    def __init__(self, dataset, hidden_channels):
        super(Experiment, self).__init__()
        
        # weight seed
        torch.manual_seed(42)
        self.conv1 = GCNConv(dataset.num_node_features, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.conv3 = GCNConv(hidden_channels, hidden_channels)
        
        # embeddings for subgraph
        self.conv4 = GCNConv(hidden_channels, hidden_channels)
        self.conv5 = GCNConv(hidden_channels, hidden_channels)
        # self.conv6 = GCNConv(hidden_channels, hidden_channels)
        # classification layer
        
        self.lin = Linear(hidden_channels*2, hidden_channels)
        self.lin2 = Linear(hidden_channels, dataset.num_classes)

    def forward(self, x, edge_index, batch, ptr):
        # Embed original
        embedding = self.conv1(x, edge_index)
        embedding = embedding.relu()
        embedding = self.conv2(embedding, edge_index)
        embedding = embedding.relu()
        embedding = self.conv3(embedding, edge_index)
        embedding = embedding.relu()
        
        # generate subgraph based on embeddings
        feature_emb = embedding.detach()
        # G = data_transformation(edge_index, feature_emb)
        # S = calculate_similarity_matrix(G)
        # clustering = AffinityPropagation(affinity='precomputed', random_state=123, max_iter=200).fit(S)
        subgraph_edge_index, _ = self.subgraph_generator(feature_emb, edge_index, batch, ptr)
        subgraph_embedding = self.conv4(embedding, subgraph_edge_index)
        subgraph_embedding = subgraph_embedding.relu()
        subgraph_embedding = self.conv5(subgraph_embedding, subgraph_edge_index)
        subgraph_embedding = subgraph_embedding.relu()
        
        # subgraph_embedding = self.conv1(x, subgraph_edge_index)
        # subgraph_embedding = subgraph_embedding.relu()
        # subgraph_embedding = self.conv2(subgraph_embedding, subgraph_edge_index)
        # subgraph_embedding = subgraph_embedding.relu()
        # subgraph_embedding = self.conv3(subgraph_embedding, subgraph_edge_index)
        # subgraph_embedding = subgraph_embedding.relu()
        
        # print(subgraph_edge_index)
        embedding = global_mean_pool(embedding, batch)
        # self.subgraph_pooling("","","")
        subgraph_embedding = global_max_pool(subgraph_embedding, batch)
        
        
        h = torch.cat((embedding, subgraph_embedding), 1)
        
        h = F.dropout(h, p=0.3, training=self.training)
        h = self.lin(h)
        h = h.relu()
        x = F.dropout(h, p=0.3, training=self.training)
        h = self.lin2(h)
        
        return embedding, h
    
    def subgraph_pooling(self, embeddings, batch, ptr):
        print('subgraph pooling')

    def subgraph_generator(self, embeddings, batch_edge_index, batch, ptr):
        '''
        Return subgraph_edge_index (edge_index of created subgraph)
        '''
        # print('processing subgraph_generator...')
        graph_counter = 0
        edge_index = [[],[]]
        subgraph_edge_index = [[],[]]
        # Gs = []
        sub_created = False
        graph_bound = {}

        for i in range(len(ptr)-1):
            graph_bound[i] = [ptr[i].item(), ptr[i+1].item()]
        
        for i, (src, dst) in enumerate(zip(batch_edge_index[0], batch_edge_index[1])):
            lower_bound = graph_bound[graph_counter][0]
            upper_bound = graph_bound[graph_counter][1]
            if ((src >= lower_bound and src < upper_bound) or
                (dst >= lower_bound and dst < upper_bound)):
                
                edge_index[0].append(src - lower_bound)
                edge_index[1].append(dst - lower_bound)
            else:
                sub_created = True
                
            if (i == len(batch_edge_index[0]) - 1) or sub_created:
                # print(f'=== Graph {graph_counter} ===')
                
                sub_created = False
                
                embs = []
                # make new graph
                for i, (b, emb) in enumerate(zip(batch, embeddings)):
                    if (b == graph_counter):
                        embs.append(emb)
                
                G = data_transformation(edge_index, embs)
                # dont need this at the moment
                # Gs.append(G)
                
                # Calculate similarity matrix
                S = calculate_similarity_matrix(G)
                
                # AP Clustering        
                # clustering = AffinityPropagation(affinity='precomputed', damping=0.9, random_state=123, max_iter=1000).fit(S)
                clustering = AffinityPropagation(affinity='precomputed', damping=0.9, random_state=123, convergence_iter=5, max_iter=100).fit(S)
                
                # Get community
                communities = {}
                for lab in clustering.labels_:
                    communities[lab] = []
                
                for nd, clust in enumerate(clustering.labels_):
                    communities[clust].append(nd)
                
                edge_index = [[],[]]
                graph_counter+=1
                
                # Make subgraph edge_index
                for c in communities:
                    w = G.subgraph(communities[c])
                    for sub in w.edges:
                        subgraph_edge_index[0].append(sub[0] + lower_bound)
                        subgraph_edge_index[1].append(sub[1] + lower_bound)
                        
                # INI LUPA WOY
                # if (graph_counter == 10):
                #     break
                
                
        # print("finished subgraph_generator")
        
        # embeddings_used = []
        # nodes_used = set(np.array(subgraph_edge_index).flatten())
        
        # for i, f in enumerate(embeddings):
        #     if(i in nodes_used):
        #         embeddings_used.append(embeddings[i].detach().numpy())
                
        
        # print("nodes used", len(nodes_used))
        # print("nodes used", (nodes_used))
        # z = torch.tensor(embeddings_used)
        # print(z.size())
        
        # return torch.tensor(subgraph_edge_index), z
        # pakai embeddings yang awal
        return torch.tensor(subgraph_edge_index), torch.tensor(embeddings)
    # (embeddings)
    
btch = None
experiment = Experiment(dataset, 64)
bcount = 0
for b in train_loader:
    # print("batch count",bcount)
    bcount+=1
    btch = b
    # print(btch.ptr)
    experiment(btch.x, btch.edge_index, btch.batch, btch.ptr)
    break
    # break
    # experiment(btch.x, btch.edge_index, btch.batch)

# print(experiment)
# experiment(btch.x, btch.edge_index, btch.batch)

In [31]:
def expTrain(train_loader, val_loader, test_loader, epoch = 2):
    import warnings
    warnings.filterwarnings("ignore", category=UserWarning) 

    experiment = Experiment(dataset, 64)

    # Train
    print('process training')
    for _ in range(epoch):
        loss = round(train_base(experiment, train_loader, True).item(), 5)
        train_acc = round(test_base(experiment, train_loader, True), 5)
        val_acc = round(test_base(experiment, val_loader, True), 5)
        
        print(f'epoch {_}; loss: {loss}; train_acc: {train_acc}; test_acc: {val_acc}')

    # Test
    print('process testing')
    test = test_base(experiment, test_loader, True)
    print(f'Accuracy: {test}')

# expTrain(train_loader, val_loader, test_loader, epoch = 1)

In [32]:
def baseTrain(train_loader, val_loader, test_loader, epoch = 10):
    base = Base(dataset, 64)

    # Train
    for _ in range(epoch):
        loss = round(train_base(base, train_loader).item(), 5)
        train_acc = round(test_base(base, train_loader), 5)
        val_acc = round(test_base(base, val_loader), 5)
        
        print(f'epoch {_}; loss: {loss}; train_acc: {train_acc}; val_acc: {val_acc}; test: {round(test_base(base, test_loader), 2)}')

    # Test
    test = test_base(base, test_loader)
    print(f'Accuracy: {test}')

#### Cross validation 10

In [33]:
from sklearn.model_selection import KFold

In [34]:
# 
train_dataset
test_dataset
k = 10

splits = KFold(n_splits=k,shuffle=True,random_state=42)
k_counter = 0

for fold, (train_idx,val_idx) in enumerate(splits.split(np.arange(len(train_dataset)))):
    # print('Fold {}'.format(fold + 1))
    # print(f'Fold',fold,'Train_idx',train_idx,'Val_idx',val_idx)
    print(f'Fold {fold}/{k}')
    #if k_counter > 2:
    #    break
    
    fold_train = []
    for key in train_idx:
        fold_train.append(dataset[key])

    fold_val = [] 
    for key in val_idx:
        fold_val.append(dataset[key])

    tr = DataLoader(fold_train, batch_size=batch_size, shuffle=False)
    vd = DataLoader(fold_val, batch_size=batch_size, shuffle=False)
    ts = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    
    # Base model
    print("=== Base model ===")
    baseTrain(tr, vd, ts, 50)
    # print("=== Experiment model ===")
    # expTrain(tr, vd, ts, 10)
    
    k_counter += 1

Fold 0/10
=== Base model ===
epoch 0; loss: 1.84328; train_acc: 0.32593; val_acc: 0.4; test: 0.26
epoch 1; loss: 0.84091; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 2; loss: 0.89693; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 3; loss: 1.08072; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 4; loss: 1.38027; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 5; loss: 0.69686; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 6; loss: 0.72891; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 7; loss: 0.82262; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 8; loss: 0.5762; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 9; loss: 0.67631; train_acc: 0.33333; val_acc: 0.4; test: 0.26
epoch 10; loss: 0.5856; train_acc: 0.66667; val_acc: 0.6; test: 0.74
epoch 11; loss: 0.59029; train_acc: 0.71111; val_acc: 0.66667; test: 0.68
epoch 12; loss: 0.81153; train_acc: 0.71852; val_acc: 0.66667; test: 0.68
epoch 13; loss: 1.25675; train_acc: 0.33333; val_acc: 0.4; test: 